# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/dsamaster
spring.datasource.username=postgres
spring.datasource.password=monil2007
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (Automatically creates tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080
spring.application.name=dsamaster

# JWT Settings
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d3e69f8c6b7593c834a5d7c8345c22
app.jwt.expiration-ms=86400000
